-- ============================================================================
-- Zillow Housing Data - Data Marts
-- ============================================================================
-- This script creates analytics-ready data marts for business intelligence
-- and reporting purposes.
-- ============================================================================
